### ISSUE TITLE
./hello_world file not found when creating REAP snapshots

### ISSUE THREAD

**Issue by varungohil** [barabanshek/sabre#4]
On running command to create REAP snapshots

`sudo env "PATH=$PATH" ./hello_world -image=docker.io/library/hello-world:latest -memsize=256 -example=start-snapshot-stop-resume-record-stop-replay-stop`

I get the output 

`env: ‘./hello_world’: No such file or directory`

I'm in sabre/vHive/sabre

**Comment by varungohil** [comment]
Correct cmd is 

`sudo env "PATH=$PATH" go run hello_world.go -image=docker.io/library/hello-world:latest -memsize=256 -example=start-snapshot-stop-resume-record-stop-replay-stop`

**Comment by varungohil** [comment]
Same change also needs to be done to te cmd for creating REAP snapshots with SAbre.

**Comment by barabanshek** [comment]
Done.
