### ISSUE TITLE
Cannot find vm.log

### ISSUE THREAD

**Issue by varungohil** [barabanshek/sabre#9]
End of the readme mentions finding results in vm.log.

But could not find it in the directory from where I ran the cmd to generate results.

**Comment by barabanshek** [comment]
it's in the place from where you run "sudo firecracker-containerd --config /etc/firecracker-containerd/config.toml 2>&1 | tee vm.log". Do you think it's clear from the instructions?

**Comment by barabanshek** [comment]
OK, clarified!
